before_install:
  - sudo systemsetup -settimezone Europe/Tallinn
  - echo -e "machine bitbucket.org\n  login fassko\n  password $CI_USER_PASSWORD" >> ~/.netrc
  - sudo gem install bundler --no-document
  - bundle install
  # - gem update fastlane --no-document
  # - fastlane --version
  # - gem update xcodeproj --no-document
  # - gem install cocoapods
  # - gem cleanup
  # - gem list
  - instruments -s devices
  - xcodebuild -showsdks
  - bundle exec pod cache clean --all
  - bundle exec pod install --repo-update
language: objective-c
osx_image: xcode9.2
script:
  - bundle exec fastlane travis
env:
  - FASTLANE_XCODE_LIST_TIMEOUT=120
notifications:
  email: false