before_install:
  - echo -e "machine bitbucket.org\n  login fassko\n  password $CI_USER_PASSWORD" >> ~/.netrc
  - gem update fastlane --no-document
  - fastlane --version
  - gem update xcodeproj --no-document
  - gem install cocoapods
  - gem cleanup
  - gem list
  - instruments -s devices
  - xcodebuild -showsdks
  - pod repo update --silent
  - pod --version
language: objective-c
osx_image: xcode8
script:
  - fastlane travis --verbose
env:
  - FASTLANE_XCODE_LIST_TIMEOUT=120