default_platform :ios


platform :ios do
  before_all do

  end

  lane :travis do
    cocoapods
    
    build
  end

  lane :build do
    xctool :build, [
      "--workspace", "TartuWeather.xcworkspace",
      "--scheme", "TartuWeather",
      "--configuration", "Debug",
      "CODE_SIGN_IDENTITY=\"\"",
      "CODE_SIGNING_REQUIRED=NO"
    ].join(" ")

    xctool :build, [
      "--workspace", "TartuWeather.xcworkspace",
      "--scheme", "TartuWeatherWidget",
      "--configuration", "Debug",
      "CODE_SIGN_IDENTITY=\"\"",
      "CODE_SIGNING_REQUIRED=NO"
    ].join(" ")
  end

  lane :release do
    cert
    sigh

    increment_build_number

    gym(
      project: "TartuWeather.xcodeproj",
      scheme: "TartuWeather",
      clean: true,
      output_name: "TartuWeather.ipa",
      include_symbols: true
    )

    dsym_zip

    copy_artifacts(
      target_path: 'artifacts',
      artifacts: ['*.dSYM.zip']
    )

    deliver
  end

  after_all do |lane|

  end

  error do |lane, exception|

  end
end
