devices([
  "iPhone SE",
  "iPhone 5s",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone Xs",
  "iPhone Xs Max"
])

languages([
  "en-US"
])

scheme "TartuWeather"
clear_previous_screenshots true
workspace "./TartuWeather.xcworkspace"
